/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bninterfacegrafica;

import java.awt.Color;
import java.net.SocketException;

import javax.swing.JOptionPane;

import bnprotocol.BnUdpServerProtcocolInterface;
import bnlogin.BnUdpLogin;
/**
 *
 * @author mvoco_000
 */
@SuppressWarnings("serial")
public class BnUdpTelaClienteChat extends javax.swing.JFrame {

    private String nickname;
    private String serverIP;
    private String serverPort;
    private String destinatario;
    private String mensagem;
    private boolean loginStatus = true;
    
    /**
     * Creates new form BnUdpTelaClienteChat
     */
    public BnUdpTelaClienteChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tIP = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        tNickname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tPorta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        tMensagem = new javax.swing.JTextField();
        bEnviarMensagem = new javax.swing.JButton();
        tDestinatario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tTodos = new javax.swing.JCheckBox();
        bLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setTitle("Login");
        jFrame1.setAlwaysOnTop(true);
        jFrame1.setName("frameLogin"); // NOI18N

        tIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIPActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("10000");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        tNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNicknameActionPerformed(evt);
            }
        });

        jLabel2.setText("IP do servidor:");

        tPorta.setText("Porta do servidor:");

        jLabel3.setText("Nome de usuário:");

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPorta)
                            .addComponent(jLabel2)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tIP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(bLogin)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLogin)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameChat"); // NOI18N

        bEnviarMensagem.setText("Enviar");
        bEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarMensagemActionPerformed(evt);
            }
        });

        tDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDestinatarioActionPerformed(evt);
            }
        });

        tChat.setEditable(false);
        tChat.setColumns(20);
        tChat.setRows(5);
        jScrollPane2.setViewportView(tChat);

        jLabel1.setText("Destinatário da mensagem:");

        tTodos.setText("Todos");
        tTodos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tTodosStateChanged(evt);
            }
        });
        tTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTodosActionPerformed(evt);
            }
        });

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        tUsuarios.setEditable(false);
        tUsuarios.setColumns(20);
        tUsuarios.setRows(5);
        jScrollPane3.setViewportView(tUsuarios);

        jLabel4.setText("Usuários Conectados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(tTodos))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEnviarMensagem))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bLogout)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTodos)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEnviarMensagem)
                            .addComponent(tDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDestinatarioActionPerformed

    private void bEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarMensagemActionPerformed
        //tChat.add() = tChat.getText() + "\n" + tMensagem.getText();
    mensagem = "02#"+ tDestinatario.getText()+"#"+tMensagem.getText();
    tChat.setText(tChat.getText()+"to "+tDestinatario.getText()+": "+ tMensagem.getText()+"\n");
                
// TODO add your handling code here:
    }//GEN-LAST:event_bEnviarMensagemActionPerformed

    private void tTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTodosActionPerformed
       
    }//GEN-LAST:event_tTodosActionPerformed

    private void tTodosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tTodosStateChanged
         if (tTodos.isSelected()) {
            tDestinatario.setText("all");
            tDestinatario.setEditable(false);
            tDestinatario.setForeground(Color.gray);
        }
        if (!tTodos.isSelected()){
           tDestinatario.setText("");
           tDestinatario.setEditable(true);
           tDestinatario.setForeground(Color.black);
        }// TODO add your handling code here:
    }//GEN-LAST:event_tTodosStateChanged

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        try {
        	String reply = null;
        	if(loginStatus){
        		reply = BnUdpLogin.getInstance().logoutAttempt(nickname, serverIP, Integer.parseInt(serverPort));
        	}else{ 
        		reply = "Desconectado(a)";
        	}	
        	switch (reply) {
			case BnUdpLogin.TIMED_OUT:
				tChat.setText(tChat.getText()+"Nao foi possivel desconectar  " + reply+ " . . .\n");
				System.out.println("Nao foi possivel desconectar  " + reply+ " . . .");
				break;
			
			case BnUdpServerProtcocolInterface.ACK_LOGOUT:
				loginStatus = false;
				tChat.setText(tChat.getText()+"Voce foi desconectado (a) . . .\n");
				System.out.println("Voce foi desconectado (a) . . . ");
				break;

			default:
				tChat.setText("Erro: " + reply+ " . . .\n");
				System.out.println("Erro: " + reply+ " . . .");
				break;
			}
		} catch (SocketException e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_bLogoutActionPerformed

    private void tIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIPActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNicknameActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed

        nickname = tNickname.getText();
        if (getNickname()=="all"){
            JOptionPane.showMessageDialog(rootPane, "Erro: all não é um nome de usuário permitido.");
        }
        String simbolosProibidos = ".;,#";
        if (getNickname().contains(simbolosProibidos))
            JOptionPane.showMessageDialog(rootPane, "Erro: o nome de usuário não deve conter os caracteres . ; , ou #");

        
        
    }//GEN-LAST:event_bLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviarMensagem;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea tChat;
    private javax.swing.JTextField tDestinatario;
    private javax.swing.JTextField tIP;
    private javax.swing.JTextField tMensagem;
    private javax.swing.JTextField tNickname;
    private javax.swing.JLabel tPorta;
    private javax.swing.JCheckBox tTodos;
    private javax.swing.JTextArea tUsuarios;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nickname
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * @return the serverIP
     */
    public String getServerIP() {
        return serverIP;
    }

    /**
     * @return the serverPort
     */
    public String getServerPort() {
        return serverPort;
    }

    /**
     * @return the destinatario
     */
    public String getDestinatario() {
        return destinatario;
    }

    /**
     * @return the mensagem
     */
    public String getMensagem() {
        return mensagem;
    }
    
    public void setIp(String ip){
    	this.serverIP = ip;
    }

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public void setServerPort(String serverPort) {
		this.serverPort = serverPort;
	}
    
}
