/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnguiclient;

import bnclient.AbstractClient;
import bnclient.BnUdpMessengerClient;
import java.io.IOException;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;

/**
 *
 * @author mvoco_000
 */
@SuppressWarnings("serial")
public class BnUdpTelaClienteJogo extends javax.swing.JFrame{

    private String ip;
    
    private int port;
    
    private String nickname;
    
    /**
     * Creates new form BnUdpTelaClienteJogo
     */
    public BnUdpTelaClienteJogo(String ip, int port, String nickname) {
        initComponents();
        this.ip = ip;
        this.port = port;
        this.nickname = nickname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDesistirPartida = new javax.swing.JButton();
        bDesistirPartida.setAction(action);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bDesistirPartida.setText("Desistir");
        /*bDesistirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesistirPartidaActionPerformed(evt);
            }
        });*/

        jLabel1.setText("Partida Aceita");

        jLabel2.setText("Desistir da partida?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bDesistirPartida)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDesistirPartida)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*private void bDesistirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesistirPartidaActionPerformed
    	System.out.println("desistir da partida . . .");
    	String data = BnUdpMessengerClient.LEAVE_GAME+"#"+nickname;
     	try {
             this.client.sendData(data);
 		} catch (IOException e) {
 	            System.err.println("Cliente error:" + e.getMessage());
 		}
    }*///GEN-LAST:event_bDesistirPartidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDesistirPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private final Action action = new LeaveGame();
    // End of variables declaration//GEN-END:variables
    
	private class LeaveGame extends AbstractAction {
		public LeaveGame() {
			putValue(NAME, "LeaveGame");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
			System.out.println("desistir da partida . . .");
			
	    	String data = BnUdpMessengerClient.LEAVE_GAME+"#"+nickname;
	     	try {
	     		
	            AbstractClient.sendData(data, ip, port);
	     		
	 		} catch (IOException exp) {
	 	            System.err.println("Cliente error:" + exp.getMessage());
	 		}
		}
	}
}
